CI: github_actions
c_compiler: vs2019
channel_sources: conda-forge
channel_targets: francoventuri main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: vs2019
extend_keys:
- ignore_build_only_deps
- extend_keys
- pin_run_as_build
- ignore_version
fmt: '10'
fortran_compiler: gfortran
gnuradio_core: 3.10.9
gnuradio_extra_pin: ''
ignore_build_only_deps:
- numpy
- python
lua: '5'
numpy: '1.23'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: 3.11.* *_cpython
r_base: '3.4'
spdlog: '1.12'
target_platform: win-64
vc: '14'
zip_keys:
- - python
  - numpy
